
version: 2

models:
  - name: book_price_history
    description: "Histórico de preços"
    columns:
      - name: date_price
      - name: day_of_month
      - name: day_of_year
      - name: week_of_year
      - name: month_of_year
      - name: month_name
      - name: month_name_short
      - name: quarter_of_year
      - name: book_id
      - name: author_id
      - name: author_name
      - name: book_name
      - name: book_category
      - name: book_price_old
      - name: book_price_new
      - name: book_discount
      - name: extraction_order
      - name: prev_price
      - name: is_price_drop
      - name: is_record_discount
  - name: dim_authors
    description: "Todos autores"
  - name: dim_books
    description: "Todos livros"